# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(2059, 1072)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(9, 9, 631, 621))
        self.graphicsView.setObjectName("graphicsView")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(9, 900, 133, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(1267, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(9, 926, 1603, 20))
        self.comboBox.setMinimumSize(QtCore.QSize(1603, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(9, 952, 474, 16))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(9, 970, 464, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(9, 996, 354, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(9, 1014, 422, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(9, 1040, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(960, 310, 261, 301))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox.setItemText(0, _translate("Dialog", "                                                    普通消息"))
        self.comboBox.setItemText(1, _translate("Dialog", "                                                    重要消息"))
        self.comboBox.setItemText(2, _translate("Dialog", "                                                    关键消息"))
        self.label.setText(_translate("Dialog", "                                                    消息类型                   "))
        self.comboBox_2.setItemText(0, _translate("Dialog", "                                                      分级指控"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "                                                      集中指控"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "                                                      mesh指控（贪婪路由）"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "                                                      mesh指控（冗余路由）"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "                                                      mesh指控（节点移动）"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "                                                      全部"))
        self.label_2.setText(_translate("Dialog", "                                                   指控模式"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "                                                            成功率"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "                                                             时延"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "                                                             通信"))
        self.pushButton_2.setText(_translate("Dialog", "开始"))
